### PR TITLE
Updated code to fail unit testing

### PR DESCRIPTION
**Pull request by Johnny2136**
Test of git flow process, changed code to fail a unit test, now putting in for code review.

### CODE REVIEW

**Review by afepps — DISMISSED** [review]
Making this change will cause the test to fail, I recommend changing series[1] back to 1.

**Comment by kfrankli** [comment]
@Johnny2136 saw the review and as noted this breaks the unit test.

**Review by mfacemire — COMMENTED** [review]
Making this change will cause unit test to fail.  Change not recommended.

**Comment by Johnny2136** [comment]
changing series[1] back to 1.

**Pull request merged**
